// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sachala.dev",
  description: "CS undergraduate. Writing about backend development and software engineering.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMono.variable} min-h-full flex flex-col bg-black text-white font-mono`}>
        
        <nav className="flex items-center justify-between px-12 py-5 border-b border-zinc-800">
          <Link href="/" className="text-white font-bold tracking-tight">
            <span className="text-blue-400">&gt;</span> sachala.dev
          </Link>
          <div className="flex gap-8 text-sm text-zinc-400">
            <Link href="/" className="hover:text-white transition-colors">home</Link>
            <Link href="/blog" className="hover:text-white transition-colors">blog</Link>
            <Link href="/contact" className="hover:text-white transition-colors">contact</Link>
          </div>
        </nav>

        <main className="flex-1">
          {children}
        </main>

        <footer className="border-t border-zinc-800 px-12 py-5 flex justify-between items-center text-xs text-zinc-600">
          <span>$ echo "built with caffeine & curiosity"</span>
          <div className="flex gap-6">
            <a href="https://linkedin.com/in/sachala-indudunu" target="_blank" className="hover:text-white transition-colors">linkedin</a>
            <a href="https://github.com/sachala-indudunu" target="_blank" className="hover:text-white transition-colors">github</a>
            <span>© 2026</span>
          </div>
        </footer>

      </body>
    </html>
  );
}